Day 1

In [1]:
yo='YoYoYooooooooooo'
print(yo)

YoYoYooooooooooo


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [3]:
data=pd.read_csv('/content/drive/MyDrive/DeepLearning_Workshop/housepricedata.csv')
df=data
data

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
0        8450            7            5          856         2         1   
1        9600            6            8         1262         2         0   
2       11250            7            5          920         2         1   
3        9550            7            5          756         1         0   
4       14260            8            5         1145         2         1   
...       ...          ...          ...          ...       ...       ...   
1455     7917            6            5          953         2         1   
1456    13175            6            6         1542         2         0   
1457     9042            7            9         1152         2         0   
1458     9717            5            6         1078         1         0   
1459     9937            5            6         1256         1         1   

      BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
0                3             8           0         548                 1  
1                3             6           1         460                 1  
2                3             6           1         608                 1  
3                3             7           1         642                 0  
4                4             9           1         836                 1  
...            ...           ...         ...         ...               ...  
1455             3             7           1         460                 1  
1456             3             7           2         500                 1  
1457             4             9           2         252                 1  
1458             2             5           0         240                 0  
1459             3             6           0         276                 0  

[1460 rows x 11 columns]

In [4]:
np.shape(np.eye(len(data)))

(1460, 1460)

In [5]:
np.hstack((data.T[1:2],data[1:2]))

array([[  7,   6,   7, ...,   1, 460,   1]])

In [6]:
LA=pd.DataFrame(data.LotArea)
LAM=np.mat(LA)
LAM

matrix([[ 8450],
        [ 9600],
        [11250],
        ...,
        [ 9042],
        [ 9717],
        [ 9937]])

In [7]:
print(type(LAM))
print(data.shape)
type(data)

<class 'numpy.matrix'>
(1460, 11)


pandas.core.frame.DataFrame

In [8]:
data.info

<bound method DataFrame.info of       LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
0        8450            7            5          856         2         1   
1        9600            6            8         1262         2         0   
2       11250            7            5          920         2         1   
3        9550            7            5          756         1         0   
4       14260            8            5         1145         2         1   
...       ...          ...          ...          ...       ...       ...   
1455     7917            6            5          953         2         1   
1456    13175            6            6         1542         2         0   
1457     9042            7            9         1152         2         0   
1458     9717            5            6         1078         1         0   
1459     9937            5            6         1256         1         1   

      BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageAre

In [9]:
data.head()

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
0     8450            7            5          856         2         1   
1     9600            6            8         1262         2         0   
2    11250            7            5          920         2         1   
3     9550            7            5          756         1         0   
4    14260            8            5         1145         2         1   

   BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
0             3             8           0         548                 1  
1             3             6           1         460                 1  
2             3             6           1         608                 1  
3             3             7           1         642                 0  
4             4             9           1         836                 1

In [10]:
df.tail()

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
1455     7917            6            5          953         2         1   
1456    13175            6            6         1542         2         0   
1457     9042            7            9         1152         2         0   
1458     9717            5            6         1078         1         0   
1459     9937            5            6         1256         1         1   

      BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
1455             3             7           1         460                 1  
1456             3             7           2         500                 1  
1457             4             9           2         252                 1  
1458             2             5           0         240                 0  
1459             3             6           0         276                 0

In [11]:
df.iloc[42:50]

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
42     9180            5            7          840         1         0   
43     9200            5            6          938         1         0   
44     7945            5            6         1150         1         0   
45     7658            9            5         1752         2         0   
46    12822            7            5         1434         1         1   
47    11096            8            5         1656         2         0   
48     4456            4            5          736         2         0   
49     7742            5            7          955         1         0   

    BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
42             2             5           0         504                 0  
43             3             5           0         308                 0  
44             3             6           0         300                 0  
45             2             6           1         576                 1  
46             1             6           1         670                 1  
47             3             7           0         826                 1  
48             2             8           0           0                 0  
49             3             6           0         386                 0

In [12]:
df.describe()

LotArea  OverallQual  OverallCond  TotalBsmtSF     FullBath  \
count    1460.000000  1460.000000  1460.000000  1460.000000  1460.000000   
mean    10516.828082     6.099315     5.575342  1057.429452     1.565068   
std      9981.264932     1.382997     1.112799   438.705324     0.550916   
min      1300.000000     1.000000     1.000000     0.000000     0.000000   
25%      7553.500000     5.000000     5.000000   795.750000     1.000000   
50%      9478.500000     6.000000     5.000000   991.500000     2.000000   
75%     11601.500000     7.000000     6.000000  1298.250000     2.000000   
max    215245.000000    10.000000     9.000000  6110.000000     3.000000   

          HalfBath  BedroomAbvGr  TotRmsAbvGrd   Fireplaces   GarageArea  \
count  1460.000000   1460.000000   1460.000000  1460.000000  1460.000000   
mean      0.382877      2.866438      6.517808     0.613014   472.980137   
std       0.502885      0.815778      1.625393     0.644666   213.804841   
min       0.000000      0.000000      2.000000     0.000000     0.000000   
25%       0.000000      2.000000      5.000000     0.000000   334.500000   
50%       0.000000      3.000000      6.000000     1.000000   480.000000   
75%       1.000000      3.000000      7.000000     1.000000   576.000000   
max       2.000000      8.000000     14.000000     3.000000  1418.000000   

       AboveMedianPrice  
count       1460.000000  
mean           0.498630  
std            0.500169  
min            0.000000  
25%            0.000000  
50%            0.000000  
75%            1.000000  
max            1.000000

In [13]:
df.isnull()

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
0       False        False        False        False     False     False   
1       False        False        False        False     False     False   
2       False        False        False        False     False     False   
3       False        False        False        False     False     False   
4       False        False        False        False     False     False   
...       ...          ...          ...          ...       ...       ...   
1455    False        False        False        False     False     False   
1456    False        False        False        False     False     False   
1457    False        False        False        False     False     False   
1458    False        False        False        False     False     False   
1459    False        False        False        False     False     False   

      BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
0            False         False       False       False             False  
1            False         False       False       False             False  
2            False         False       False       False             False  
3            False         False       False       False             False  
4            False         False       False       False             False  
...            ...           ...         ...         ...               ...  
1455         False         False       False       False             False  
1456         False         False       False       False             False  
1457         False         False       False       False             False  
1458         False         False       False       False             False  
1459         False         False       False       False             False  

[1460 rows x 11 columns]

In [14]:
df.isnull().sum()

LotArea             0
OverallQual         0
OverallCond         0
TotalBsmtSF         0
FullBath            0
HalfBath            0
BedroomAbvGr        0
TotRmsAbvGrd        0
Fireplaces          0
GarageArea          0
AboveMedianPrice    0
dtype: int64

In [15]:
df.dropna()

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
0        8450            7            5          856         2         1   
1        9600            6            8         1262         2         0   
2       11250            7            5          920         2         1   
3        9550            7            5          756         1         0   
4       14260            8            5         1145         2         1   
...       ...          ...          ...          ...       ...       ...   
1455     7917            6            5          953         2         1   
1456    13175            6            6         1542         2         0   
1457     9042            7            9         1152         2         0   
1458     9717            5            6         1078         1         0   
1459     9937            5            6         1256         1         1   

      BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
0                3             8           0         548                 1  
1                3             6           1         460                 1  
2                3             6           1         608                 1  
3                3             7           1         642                 0  
4                4             9           1         836                 1  
...            ...           ...         ...         ...               ...  
1455             3             7           1         460                 1  
1456             3             7           2         500                 1  
1457             4             9           2         252                 1  
1458             2             5           0         240                 0  
1459             3             6           0         276                 0  

[1460 rows x 11 columns]

In [16]:
#alt way
np.isnan(df.values).any()

False

In [17]:
nums=np.array([1,2,3,4,5])
type(nums)

numpy.ndarray

In [18]:
x=df.iloc[:,0:-1].values
y=df.iloc[:,-1].values

In [19]:
x

array([[ 8450,     7,     5, ...,     8,     0,   548],
       [ 9600,     6,     8, ...,     6,     1,   460],
       [11250,     7,     5, ...,     6,     1,   608],
       ...,
       [ 9042,     7,     9, ...,     9,     2,   252],
       [ 9717,     5,     6, ...,     5,     0,   240],
       [ 9937,     5,     6, ...,     6,     0,   276]])

In [20]:
y

array([1, 1, 1, ..., 1, 0, 0])

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [22]:
from sklearn import preprocessing 
min_max_scaler=preprocessing.MinMaxScaler()
x_scale=min_max_scaler.fit_transform(x_train)

In [23]:
x_scale

array([[0.0331861 , 0.44444444, 0.625     , ..., 0.25      , 0.        ,
        0.20733427],
       [0.03055458, 0.55555556, 0.75      , ..., 0.41666667, 0.33333333,
        0.26798307],
       [0.03494823, 0.44444444, 0.75      , ..., 0.16666667, 0.        ,
        0.        ],
       ...,
       [0.0321204 , 0.44444444, 0.75      , ..., 0.25      , 0.        ,
        0.40338505],
       [0.02964313, 0.66666667, 0.875     , ..., 0.41666667, 0.33333333,
        0.15232722],
       [0.01114305, 0.66666667, 0.5       , ..., 0.41666667, 0.33333333,
        0.46544429]])

In [24]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1168, 10)
(1168,)
(292, 10)
(292,)


In [25]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=0)

In [26]:
y_pred=classifier.predict(x_test)

In [27]:
print(y_pred)

[0 1 0 0 1 0 0 1 0 0 0 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 0 1 0 1
 1 1 0 0 1 0 1 0 1 0 0 1 0 0 1 0 1 1 1 1 0 1 0 0 0 1 1 1 0 0 1 0 1 0 0 0 0
 1 1 1 1 0 0 0 1 0 0 0 0 1 1 0 1 0 1 0 1 0 1 0 1 1 1 1 1 1 0 0 1 0 1 0 1 0
 0 0 0 1 0 0 0 1 1 1 0 1 0 1 0 1 0 0 1 1 1 1 0 0 1 1 0 1 1 1 0 1 1 1 0 0 1
 0 0 0 1 1 1 0 0 1 1 0 0 1 0 1 0 0 1 1 1 1 1 1 0 0 0 1 1 1 1 0 1 0 0 0 0 1
 1 1 1 1 0 0 0 0 0 1 0 1 0 1 0 1 1 0 1 1 0 1 0 1 0 1 1 0 1 1 1 1 0 1 1 0 1
 0 0 1 0 1 0 0 0 0 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 1 1 0 0 1 1 0 0 1
 1 1 0 0 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 1 0 1 0 1 0 1 0 1 1 0 0]


In [28]:
from sklearn.metrics import accuracy_score 
print("Accuracy Score is: \n",accuracy_score(y_test,classifier.predict(x_test))*100)

Accuracy Score is: 
 81.5068493150685
