In [15]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.datasets import load_iris
#data=load_iris()

In [17]:
data=load_iris()
df=pd.DataFrame(data.data,columns=data.feature_names)
df['Class']=data.target_names[data.target]
df.head()
x=df.iloc[:,:-1].values
y=df.Class.values
print(x[:5])
print(y[:5])
#continue
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)
pred=knn.predict(x_test)
print(pred)
#continue
from sklearn.metrics import accuracy_score,confusion_matrix
print("Training Accuracy Score\n",accuracy_score(y_train,knn.predict(x_train)))
print("Testing Accuracy Score\n",accuracy_score(y_test,knn.predict(x_test)))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
['setosa' 'setosa' 'setosa' 'setosa' 'setosa']
['versicolor' 'setosa' 'virginica' 'virginica' 'versicolor' 'virginica'
 'setosa' 'setosa' 'versicolor' 'virginica' 'virginica' 'versicolor'
 'virginica' 'virginica' 'setosa' 'versicolor' 'virginica' 'versicolor'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'versicolor' 'virginica'
 'versicolor' 'virginica' 'setosa' 'virginica' 'versicolor']
Training Accuracy Score
 0.975
Testing Accuracy Score
 0.9666666666666667


In [10]:
df=pd.DataFrame(data.data,columns=data.feature_names) 
df['Class']=data.target_names[data.target]
df.head()
x=df.iloc[:,:-1].values 
y=df.Class.values
print(x[:5])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
['setosa' 'setosa' 'setosa' 'setosa' 'setosa']


In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)
pred=knn.predict(x_test)
print(pred)

['setosa' 'virginica' 'virginica' 'virginica' 'setosa' 'virginica'
 'setosa' 'versicolor' 'setosa' 'virginica' 'virginica' 'setosa' 'setosa'
 'virginica' 'setosa' 'setosa' 'versicolor' 'versicolor' 'setosa' 'setosa'
 'setosa' 'virginica' 'setosa' 'versicolor' 'virginica' 'setosa'
 'versicolor' 'versicolor' 'versicolor' 'versicolor']


In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix
print("Accuracy score of training data is: \n",accuracy_score(y_train,knn.predict(x_train)))
print("Accuracy score of testing data is: \n",accuracy_score(y_test,knn.predict(x_test)))
print("Confusion Matrix of training data is: \n",confusion_matrix(y_train,knn.predict(x_train)))
print("Confusion Matrix of testing data is: \n",confusion_matrix(y_test,knn.predict(x_test)))

Accuracy score of training data is: 
 0.9833333333333333
Accuracy score of testing data is: 
 0.9666666666666667
Confusion Matrix of training data is: 
 [[37  0  0]
 [ 0 40  1]
 [ 0  1 41]]
Confusion Matrix of testing data is: 
 [[13  0  0]
 [ 0  8  1]
 [ 0  0  8]]
